//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostelManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alotment
    {
        public int AlottmentID { get; set; }
        public string stuID { get; set; }
        public Nullable<int> roomID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> DateOfAllotment { get; set; }
        public Nullable<System.DateTime> DateOfClearance { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual Room Room1 { get; set; }
        public virtual Room Room2 { get; set; }
        public virtual Student Student { get; set; }
        public virtual Student Student1 { get; set; }
        public virtual Student Student2 { get; set; }
    }
}
