//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostelManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Alotments = new HashSet<Alotment>();
            this.Alotments1 = new HashSet<Alotment>();
            this.Alotments2 = new HashSet<Alotment>();
        }
    
        public string CNIC { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateOFBirth { get; set; }
        public string ContactNo { get; set; }
        public Nullable<int> BGid { get; set; }
        public Nullable<int> Cityid { get; set; }
        public Nullable<double> CGPA { get; set; }
        public string Session { get; set; }
        public Nullable<int> Deptid { get; set; }
        public Nullable<int> loginID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alotment> Alotments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alotment> Alotments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alotment> Alotments2 { get; set; }
        public virtual BloodGroup BloodGroup { get; set; }
        public virtual BloodGroup BloodGroup1 { get; set; }
        public virtual BloodGroup BloodGroup2 { get; set; }
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        public virtual City City2 { get; set; }
        public virtual Department Department { get; set; }
        public virtual Department Department1 { get; set; }
        public virtual Department Department2 { get; set; }
        public virtual Login Login { get; set; }
        public virtual Login Login1 { get; set; }
        public virtual Login Login2 { get; set; }
    }
}
