INSERT INTO BloodGroup(Name)
VALUES('A+')
INSERT INTO BloodGroup(Name)
VALUES('A-')
INSERT INTO BloodGroup(Name)
VALUES('B+')
INSERT INTO BloodGroup(Name)
VALUES('B-')
INSERT INTO BloodGroup(Name)
VALUES('AB+')
INSERT INTO BloodGroup(Name)
VALUES('AB-')
INSERT INTO BloodGroup(Name)
VALUES('O+')
INSERT INTO BloodGroup(Name)
VALUES('O-')