INSERT INTO Residents(Name)
VALUES('boy')
INSERT INTO Residents(Name)
VALUES('girl')
INSERT INTO Residents(Name)
VALUES('faculity')
INSERT INTO Residents(Name)
VALUES('student')
INSERT INTO Residents(Name)
VALUES('guests')
