INSERT INTO RoomType(RoomType)
VALUES('Cubical')
INSERT INTO RoomType(RoomType)
VALUES('Biseater')
INSERT INTO RoomType(RoomType)
VALUES('Triseater')
INSERT INTO RoomType(RoomType)
VALUES('Fourseater')
INSERT INTO RoomType(RoomType)
VALUES('Five-seater')
INSERT INTO RoomType(RoomType)
VALUES('Six-seater')
INSERT INTO RoomType(RoomType)
VALUES('Multi-seater')
