INSERT INTO Departments(Name)
VALUES('Computer Science')
INSERT INTO Departments(Name)
VALUES('Electrical Engineering')
INSERT INTO Departments(Name)
VALUES('Mechanical Engineering')
INSERT INTO Departments(Name)
VALUES('Civil Engineering')
INSERT INTO Departments(Name)
VALUES('City and Regional Planning')
INSERT INTO Departments(Name)
VALUES('Environmental Engineering')
INSERT INTO Departments(Name)
VALUES('Product and Industrial Design')
